[build]
builder = "python"
buildCommand = "pip install -r requirements.txt"

[start]
startCommand = "gunicorn quickfeedback.wsgi:application --bind 0.0.0.0:$PORT"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
